mutation UpdateProfile($rkey: String!, $input: OrgAtmosphereconfProfileInput!) {
  updateOrgAtmosphereconfProfile(rkey: $rkey, input: $input) {
    id
    uri
    cid
    did
    actorHandle
    displayName
    description
    avatar {
      ref
      mimeType
      size
      url
    }
    homeTown {
      name
      value
    }
    interests
    createdAt
    indexedAt
  }
}
