query GetProfile($handle: String!) {
    orgAtmosphereconfProfiles(
        where: { actorHandle: { eq: $handle } }
        first: 1
    ) {
        edges {
            node {
                id
                uri
                cid
                did
                actorHandle
                displayName
                description
                avatar {
                    ref
                    mimeType
                    size
                    url(preset: "avatar")
                }
                homeTown {
                    name
                    value
                }
                interests
                createdAt
                indexedAt
            }
        }
    }
}
